global_config:
  # all global configs can be overridden inside each backup config
  encryption_enabled: false
  encryption_password: ""
  compression_enabled: true

  skip_tables: ["logs", "cache"]
  dump_options: ["--no-create-info"]

  schedule: "0 0 * * *" # Run every day at midnight

db_connections:
  - id: "production_db"
    hostname: "production-db"
    port: 3306
    username: "prod_user"
    password: "prodpassword"
    database: "production_db"

backups:
  - id: "production_scp_backup"
    host_id: "primary_scp"
    db_connection_id: "staging_db"
    path: "/home/wise-fox/files"
    encryption_enabled: true
    encryption_password: "passwordthatishardtoguess"
    schedule: "*/1 * * * *" # Run every minute
    notify_on_fail: true
    notify_on_success: true
    notification_ids: ["email_notification", "discord_notification"]

  - id: "staging_scp_backup"
    db_connection_id: "staging_db"
    host_id: "primary_scp"
    path: "/home/wise-fox/files"
    schedule: "*/5 * * * *" # Run every 5 minutes
    notify_on_fail: true
    notify_on_success: false
    notification_ids: ["email_notification", "discord_notification"]

  - id: "production_local_backup"
    db_connection_id: "production_db"
    local: true
    path: "/dbackup/storage"
    schedule: "*/1 * * * *" # Run every minute

notifications:
  - id: "discord_notification"
    method: "discord"
    discord_webhook_url: ""

  - id: "email_notification"
    method: "email"
    smtp_server: ""
    smtp_port: 465
    smtp_user: ""
    smtp_password: ""
    smtp_recipient: ""
    smtp_sender: ""
    smtp_recipients: [""]
    smtp_use_ssl: true
    smtp_use_tls: false
