global_config:
  # all global configs can be overridden inside each backup config
  encryption_enabled: false
  encryption_password: ""
  compression_enabled: true

  skip_tables: "logs, cache"

  schedule: "0 0 * * *" # Run every day at midnight

db_connections:
  - name: "staging_db"
    host: "db"
    port: 3306
    username: "staging_user"
    password: "stagingpassword"
    database: "staging_db"

  - name: "production_db"
    host: "production-db.example.com"
    port: 3306
    username: "prod_user"
    password: "prodpassword"
    database: "production_db"

hosts:
  - name: "primary_scp"
    host: "ssh-sftp-ftp-server"
    username: "wise-fox"
    password: "9Jp*2Lv@4zQ"
    protocol: "scp"
    port: 22

  - name: "primary_sftp"
    host: "ssh-sftp-ftp-server"
    username: "wise-fox"
    password: "9Jp*2Lv@4zQ"
    protocol: "sftp"
    port: 22

  - name: "primary_ftp"
    host: "ssh-sftp-ftp-server"
    username: "agile-badger"
    password: "6Hv9]3kJt!^"
    protocol: "ftp"
    port: 21

backup:
  - name: "staging_scp_backup"
    host: "primary_scp"
    path: "/home/wise-fox/files"
    db_connection: "staging_db"
    skip_tables: "logs, cache"
    schedule: "*/1 * * * *" # Run every minute

  - name: "staging_sftp_backup"
    host: "primary_sftp"
    path: "/home/wise-fox/files"
    db_connection: "staging_db"
    skip_tables: "logs, cache"
    schedule: "*/1 * * * *" # Run every minute

  - name: "staging_ftp_backup"
    host: "primary_ftp"
    path: "/files/ftp"
    db_connection: "staging_db"
    encryption_enabled: true
    encryption_password: "strongencryptionkey"
    skip_tables: "logs, cache"
    schedule: "*/1 * * * *" # Run every minute

notifications:
  - method: "email" # none, email
    notify_on_fail: true
    notify_on_success: false
    smtp_server: "smtp.example.com"
    smtp_port: 587
    smtp_user: "notification@example.com"
    smtp_password: "securepassword123"
    smtp_recipient: "admin@example.com"
