global_config:
  # all global configs can be overridden inside each backup config
  encryption_enabled: false
  encryption_password: ""
  compression_enabled: true

  skip_tables: ["logs", "cache"]
  dump_options: ["--no-create-info"]

  schedule: "0 0 * * *" # Run every day at midnight

db_connections:
  - name: "staging_db"
    host: "staging-db"
    port: 3306
    username: "staging_user"
    password: "stagingpassword"
    database: "staging_db"

  - name: "production_db"
    host: "production-db"
    port: 3306
    username: "prod_user"
    password: "prodpassword"
    database: "production_db"

hosts:
  - name: "primary_scp"
    host: "ssh-sftp-ftp-server"
    username: "wise-fox"
    password: "9Jp*2Lv@4zQ"
    protocol: "scp"
    port: 22

backup:
  - name: "production_scp_backup"
    host: "primary_scp"
    path: "/home/wise-fox/files"
    encryption_enabled: true
    encryption_password: "passwordthatishardtoguess"
    db_connection: "staging_db"
    schedule: "*/1 * * * *" # Run every minute
    notifications: ["email_notification", "discord_notification"]

  - name: "staging_scp_backup"
    host: "primary_scp"
    path: "/home/wise-fox/files"
    db_connection: "staging_db"
    schedule: "*/5 * * * *" # Run every 5 minutes
    notifications: ["email_notification", "discord_notification"]

  - name: "production_local_backup"
    local: true
    path: "/var/tmp"
    db_connection: "production_db"
    schedule: "*/1 * * * *" # Run every minute

notifications:
  - name: "email_notification"
    method: "email" # email, discord
    notify_on_fail: true
    notify_on_success: false
    smtp_server: ""
    smtp_port: 587
    smtp_user: ""
    smtp_password: ""
    smtp_sender: ""
    smtp_recipients: [""]
    smtp_use_ssl: true
    smtp_use_tls: false
