name: "dbackup-dev"
services:
  dbackup:
    container_name: dbackup
    build: ../.
    volumes:
      - ../src/.:/dbackup/
      - ../config.yaml:/dbackup/config/config.yaml
    environment:
      TZ: Europe/Zurich
    entrypoint: ["sh", "-c", "while :; do sleep 2073600; done"]

  staging-db:
    image: mysql:8.0
    container_name: staging-db
    volumes:
      - ./seed_prod_db.sql:/docker-entrypoint-initdb.d/seed.sql
    environment:
      TZ: Europe/Zurich
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: staging_db
      MYSQL_USER: staging_user
      MYSQL_PASSWORD: stagingpassword

  production-db:
    image: mysql:8.0
    container_name: production-db
    volumes:
      - ./seed_prod_db.sql:/docker-entrypoint-initdb.d/seed.sql
    environment:
      TZ: Europe/Zurich
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: production_db
      MYSQL_USER: prod_user
      MYSQL_PASSWORD: prodpassword

  server:
    container_name: ssh-sftp-ftp-server
    build: .
    ports:
      - "22:22"
      - "21:21"
    environment:
      TZ: Europe/Zurich
